os:
  - linux

before_install:
  - sudo apt-get install git-svn

language: csharp
mono: none
dotnet: 2.0.0
script:
 - dotnet tool install -g Cake.Tool
 - dotnet cake --target=all

deploy:
  provider: releases
  api_key: $AUTH_TOKEN
  file:
   - "dist/ubuntu-x64/svn2gitnet-ubuntu-x64.tar.gz"
   - "dist/centos-x64/svn2gitnet-centos-x64.tar.gz"
   - "dist/debian-x64/svn2gitnet-debian-x64.tar.gz"
   - "dist/fedora-x64/svn2gitnet-fedora-x64.tar.gz"
   - "dist/rhel-x64/svn2gitnet-rhel-x64.tar.gz"
   - "dist/osx-x64/svn2gitnet-osx-x64.tar.gz"
  skip_cleanup: true
  on:
    tags: true